// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gbvffegzigglgelvekeq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdidmZmZWd6aWdnbGdlbHZla2VxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5MTU2MDIsImV4cCI6MjA2NDQ5MTYwMn0.0dt1ZA8KjqGa3tlrqxFw9QMPlj139fMmd-E8IH1s-80";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});